name: Firebase functions Build & Test

on: [push]

jobs:
  functions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and Test /functions
      working-directory: functions
      run: |
        npm install firebase-cli -g
        firebase setup:emulators:firestore
        npm ci
        npm run build
        npm test
      env:
        CI: true